FROM eclipse-temurin:21-jre

WORKDIR /app

# Копируем WAR файл под именем profiler.war
COPY qubership-profiler-profiler-3.1.3-SNAPSHOT.war profiler.war

# Устанавливаем переменную окружения для отключения SO_LINGER (решение проблемы с SocketException)
ENV SERVER_TOMCAT_SO_LINGER=0

# Открываем порт (обычно 8180 для Spring Boot, но можно изменить)
EXPOSE 8180

# Entrypoint для запуска WAR файла
ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7779" , "-jar", "profiler.war"]

